"""Add resource inventory

Revision ID: 5a0d3dc322c4
Revises: 69563a885d0a
Create Date: 2026-07-30 18:34:28.541819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0d3dc322c4'
down_revision: Union[str, Sequence[str], None] = '69563a885d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('warehouse', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_inventory_id'), 'resource_inventory', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_inventory_id'), table_name='resource_inventory')
    op.drop_table('resource_inventory')
    # ### end Alembic commands ###
