"""Update disaster events

Revision ID: 9aa4a3422f50
Revises: c7e9604a5321
Create Date: 2026-07-30 19:08:11.880689

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9aa4a3422f50'
down_revision: Union[str, Sequence[str], None] = 'c7e9604a5321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_events', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('disaster_events', sa.Column('status', sa.String(), nullable=True))
    op.add_column('disaster_events', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('disaster_events', 'disaster_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('disaster_events', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('disaster_events', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disaster_events', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('disaster_events', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('disaster_events', 'disaster_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('disaster_events', 'source')
    op.drop_column('disaster_events', 'status')
    op.drop_column('disaster_events', 'severity')
    # ### end Alembic commands ###
